const express=require('express');
const { asignup, alogin, addjobinadmin, getalljobsinadmin, alluserListing, fetchbycity, fetchbyjobid, fetchjobbyuser } = require('../../controllers/admincontroller');
const router=express.Router();
router.post('/signup',asignup);
router.post('/login',alogin);
router.post('/add',addjobinadmin);
router.get('/get',getalljobsinadmin);
router.get('/getuser',alluserListing);
router.get('/getcity/:city',fetchbycity);
router.get('/fetch/:jid',fetchbyjobid);
router.get('/extract/:uid',fetchjobbyuser);
// router.post('/signup',(req,res)=>{asignup});
// router.post('/login',(req,res)=>{alogin});
// router.post('/add',(req,res)=>{addjobinadmin});
// router.get('/get',(req,res)=>{getalljobsinadmin});
// router.get('/getuser',(req,res)=>{alluserListing});
// router.get('/getcity/:city',(req,res)=>{fetchbycity});
// router.get('/fetch/:jid',(req,res)=>{fetchbyjobid});
// router.get('/extract/:uid',(req,res)=>{fetchjobbyuser});
module.exports=router;